Add integration tests
GitGuardian/src-fingerprint pull request #43
Opened 2022-02-01 15:30 UTC by pierrelalanne

2022-02-02 13:58 UTC, agateau-gg commented
I am worried a bash-based script is going to cause trouble when you try to run the tests on Windows. Maybe you can use pytest? It would give you better cross-platform support and nicer reports. Or maybe there is some Go-friendly tools to write integration tests?

2022-02-02 14:45 UTC, pierrelalanne commented
> I am worried a bash-based script is going to cause trouble when you try to run the tests on Windows. Maybe you can use pytest? It would give you better cross-platform support and nicer reports. Or maybe there is some Go-friendly tools to write integration tests?

I understand, but the tests written in this issue are meant to run only in the CI to check that developments don't break the core feature of the package.

2022-02-02 15:19 UTC, pierrelalanne commented
> > > I am worried a bash-based script is going to cause trouble when you try to run the tests on Windows. Maybe you can use pytest? It would give you better cross-platform support and nicer reports. Or maybe there is some Go-friendly tools to write integration tests?
> > 
> > 
> > I understand, but the tests written in this issue are meant to run only in the CI to check that developments don't break the core feature of the package.
> 
> Sure, but you would want to know early if said developments break something on Windows, no? Especially if no developer actively uses the tool on Windows.

I think I don't understand. The tests ran are purely functional, maybe they should be named "validation tests" or "functional tests". Their only goal is to validate that `src-fingerprint` behaves as expected from end to end especially in its interaction with GitHub. I don't see how it is platform dependant. Or maybe you are suggesting to have additional tests for each platform supported ?

2022-02-02 15:27 UTC, agateau-gg commented
My point is: if the action performed in the tests can be performed on Windows, then it should be tested on Windows. Even if we can't think of a reason for them to fail on Windows. They should also be tested on macOS for the same reason.
Luckily it's not much work to do for a static binary like src-fingerprint (GitHub already provides the required runners).

2022-02-02 18:11 UTC, agateau-gg requested changes

2022-02-02 18:11 UTC, agateau-gg commented on .github/workflows/test.yml
> +    runs-on: ubuntu-latest
You can avoid the duplication by defining a test matrix. Something like this:

```yaml
  integration-tests:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # (...)
```

2022-02-02 18:13 UTC, agateau-gg commented
> Tests portability to other platforms seemed like a slightly different topic to me

It's not the tests which must be portable: it's the app. Running the app tests on all platforms is the best way to ensure the app is and remains portable.

2022-02-03 08:35 UTC, agateau-gg commented
To illustrate what I have in mind when I talk about using pytest, I rewrote your first two tests. It would look like this: https://gist.github.com/agateau-gg/84739a6ea6c97e818cecd04eda0a22d0

With this file in your `tests` directory, you just `pip install pytest` and run `pytest tests`. I think it would be more convenient to write tests this way. (It should also be more convenient for others to read them! :wink: )

Second test fails for me because my token does not have access to the private repositories required here. This could be problematic because it means no one but people with tokens similar to the one on the CI can run the tests. I don't have a solution for this though, since the nature of the product is tied to the way GitHub private repositories work :thinking:

2022-02-03 10:29 UTC, pierrelalanne commented
I updated the MR accordingly.

2022-02-03 12:07 UTC, agateau-gg approved these changes
Looks good now! Do you know why the tests do not pass though? Is there any issue with the token?

2022-02-04 14:02 UTC, merged