Add integration tests bitbucket
GitGuardian/src-fingerprint pull request #55
Opened 2022-02-28 18:37 UTC by pierrelalanne

In this PR :  
- we add integration tests for BitBucket
- we clean some logging

2022-03-01 14:34 UTC, Walz requested changes

2022-03-01 14:34 UTC, Walz commented on tests/integration_test.py
> +    assert output_repos == {"src fingerprint test", "main-test-repo"}
You don't use `expected_output_repos`
```suggestion
@pytest.mark.parametrize(
    "title, cmd_args, expected_output_repos", [
        (
            "Get all repos accesible to integration tests token for project 'src fingerprint'",
            ["--limit", "10","--object", "src fingerprint"], 
            {"src fingerprint test", "main-test-repo"},
        ),
    ]
)
def test_src_fingerprint_bitbucket_object_specified(title, cmd_args, expected_output_repos):
    output = run_src_fingerprint(
        provider="bitbucket",
        token = BITBUCKET_INTEGRATION_TESTS_TOKEN,
        args=cmd_args+["--provider-url", BITBUCKET_INTEGRATION_TESTS_URL]
    )
    output_repos = get_output_repos("fingerprints.jsonl")
    os.remove("fingerprints.jsonl")
    assert output_repos == expected_output_repos
```

2022-03-01 14:34 UTC, Walz commented on tests/integration_test.py
> +    assert len(output_repos) == 10
`expected_output_repos` could be replaced with `number_of_expected_output_repos` to make the test parametrizable.

2022-03-01 15:12 UTC, pierrelalanne commented
Should be good now, successful pipeline [here](https://github.com/pierrelalanne/src-fingerprint/runs/5377277137?check_suite_focus=true).

2022-03-03 09:08 UTC, pierrelalanne commented
@Walz, I updated the MR, can you have a look ? Thx

2022-03-03 09:30 UTC, Walz approved these changes

2022-03-03 10:09 UTC, merged